name: Build LaTeX document
on:
  push:
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Mafia-the-Game.tex
          latexmk_use_xelatex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*.pdf"
          commit_message: "chore(build): auto-generate pdf"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
